# action.yml
name: 'Jekyll Plantuml Build Action'
description: Jekyll Site Build Action that includes local PlantUML diagram generation
inputs:
  path:  
    description: 'Path to the checkout'
    required: true
    default: '.'
outputs:
  time: # id of output
    description: 'The time the build completed'
runs:
  using: 'docker'
  image: docker://ghcr.io/hackinghat/jekyll-plantuml-build-action:0.0.1
  args:
    - build ${{ inputs.path }}
