# action.yml
name: 'Jekyll Plantuml Build Action'
description: Jekyll Site Build Action that will generate PlantUML, Mermaid and MathJax local assets 
inputs:
  path:  
    description: 'Path to the checkout'
    required: true
    default: '.'
  token:
    description: 'The github token to use'
    required: false
outputs:
  time: # id of output
    description: 'The time the build completed'
runs:
  using: 'docker'
  image: docker://ghcr.io/hackinghat/jekyll-local-diagram-build-action:0.1.0
  args:
    - build 
    - ${{ inputs.path }}
